### ISSUE TITLE
Secrete Shown in Drone

### ISSUE THREAD

**Issue by zottelchin** [drone-plugins/drone-webhook#28]
I set a secrete with my webhook_urls and everything works fine. The only problem is that in drone, the url is shown in plain. As my api key is in the url, thats not very convenient.

**Comment by lawrsp** [comment]
@zottelchin  how did you get the secret into urls? 

I tried
```yaml
notify:
    image: plugins/webhook
    secrets: [ webhook_access_token ]
    urls: https://.......?access_token=${WEBHOOK_ACCESS_TOKEN}
    template: "build status {{ build.status }}
```
it does not work,
and I tried
```yaml
notify:
    image: plugins/webhook
    secrets: 
          - source: webhook_access_token
            target: webhook_password
    urls: https://.......?access_token=${WEBHOOK_PASSWORD}
    template: "build status {{ build.status }}
```
still not work

**Comment by zottelchin** [comment]
I have the complete url as a secrete. If you use the secretes from the [Documentation](http://plugins.drone.io/drone-plugins/drone-webhook/#secret-reference) you can use the first deploy methode, in all other cases you have to rename it to the right name (like in the dev deploy). 

```
deploy:
    image: plugins/webhook
    secrets: [ webhook_urls ]
    when:
      branch: master
  deploy Dev:
    image: plugins/webhook
    secrets:
      - source: webhook_dev_url
target: webhook_urls
```
