### ISSUE TITLE
it there a way to pass secrets to url query?

### ISSUE THREAD

**Issue by lawrsp** [drone-plugins/drone-webhook#33]
some apis need to pass a access_token to get authed

I tried
```yaml
notify:
    image: plugins/webhook
    secrets: [ webhook_access_token ]
    urls: https://.......?access_token=${WEBHOOK_ACCESS_TOKEN}
    template: "build status {{ build.status }}
```
it does not work,
and I tried
```yaml
notify:
    image: plugins/webhook
    secrets: 
          - source: webhook_access_token
            target: webhook_password
    urls: https://.......?access_token=${WEBHOOK_PASSWORD}
    template: "build status {{ build.status }}
```
still not work
