### ISSUE TITLE
Can't resolve services dns names when run inside kubernetes

### ISSUE THREAD

**Issue by mayfield** [drone-plugins/drone-webhook#38]
Drone Version: `1.0.0-rc3`

Most likely this issue stems from the drone agent but I wanted to start here since this is where the problem first starts and I'm trying to not make too many assumptions.

I have a kubernetes service and pod that handles drone webhook POSTs but I'm unable to use this service's DNS name from my drone pipeline.  Instead the step fails with this error...

```
Error: Failed to execute the HTTP request. Post http://integration-bot/drone: dial tcp: lookup integration-bot on 127.0.0.11:53: no such host
2019/01/11 20:53:30 Post http://integration-bot/drone: dial tcp: lookup integration-bot on 127.0.0.11:53: no such host
```

Here is the relevant pipeline step: 
```yaml
- name: notify
  image: plugins/webhook
  settings:
    urls: http://integration-bot-app/drone
  when:
    status:
    - success
    - failure
```

Note that `integration-bot-app` is made available as a service in the same namespace.  Here is a snippit of me testing the service from my standalone drone pod...
```
:; kubectl exec -it -n integration drone-app-7885955ffc-f8k6n sh
/ # wget http://integration-bot-app/
Connecting to integration-bot-app (172.20.207.235:80)
wget: server returned error: HTTP/1.1 404 Not Found
/ # command terminated with exit code 1
```

The 404 is a "success" in this case.  DNS resolved, and the server answered the query with a 404 as expected for a `GET /`.
