### ISSUE TITLE
issue, how to send the overall pipeline status?

### ISSUE THREAD

**Issue by theautomation** [drone-plugins/drone-webhook#63]
Hi, i have multiple pipelines in my drone config file. How can i send the overall build status en not just the pipeline status. The code below sends only the pipeline build status. 

```
---
kind: pipeline
name: notify webhook

steps:
  - name: send
    image: plugins/webhook
    settings:
      username:
        from_secret: nodered_endpoint_username
      password:
        from_secret: nodered_endpoint_password
      urls: http://***drone/notify
      skip_verify: true
      content_type: application/json
      template: |
        {
          "owner": "{{ repo.owner }}",
          "repo": "{{ repo.name }}",
          "status": "{{ build.status }}",
          "build number": "{{ build.number }}",
          "build link": "{{ build.link }}"
        }
    when:
      status:
      - success
      - failure
```

the full config file

```
---
kind: pipeline
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint . 

  - name: docker-compose
    image: tmaier/docker-compose:latest
    commands:
      - docker-compose config -q

---
kind: pipeline
type: docker
name: build

depends_on:
  - validate

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker-registry-username
      password:
        from_secret: docker-registry-password
      registry: docker-registry.theautomation.nl
      repo: docker-registry.theautomation.nl/coen/prd-${DRONE_REPO_NAME}-app
      auto_tag: true

---
kind: pipeline
type: docker
name: upgrade

depends_on:
  - build

steps:
  - name: git pull
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd /home/coen/docker-home-services/${DRONE_REPO_NAME}/
        - git pull

  - name: docker compose up
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd /home/coen/docker-home-services/${DRONE_REPO_NAME}/
        - docker-compose up -d

  - name: cleanup
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      script:
        - cd /home/coen/docker-home-services/${DRONE_REPO_NAME}/
        - docker image prune -f

---
kind: pipeline
name: notify webhook

steps:
  - name: send
    image: plugins/webhook
    settings:
      username:
        from_secret: nodered_endpoint_username
      password:
        from_secret: nodered_endpoint_password
      urls: http://***drone/notify
      skip_verify: true
      content_type: application/json
      template: |
        {
          "owner": "{{ repo.owner }}",
          "repo": "{{ repo.name }}",
          "status": "{{ build.status }}",
          "build number": "{{ build.number }}",
          "build link": "{{ build.link }}"
        }
    when:
      status:
      - success
      - failure
```

I have ask the same question on [discourse.drone.io ](https://discourse.drone.io/t/pipeline-failure-but-build-status-success/9536) but have no answer yet.
